### ISSUE TITLE
CORS request rejected when logging in with solid.community identity

### ISSUE THREAD

**Issue by almereyda** [scenaristeur/agora#1]
## Observed behaviour

When attempting to login to

- https://scenaristeur.github.io/agora/
- https://scenaristeur.github.io/salut/
- https://scenaristeur.github.io/compagent-tuto/

nothing happens after providing the URL of the WebID and clicking Go.

The browser console reveals, that the CORS request failed.
Apparently the same-origin rule prohibites to load external content.

## Expected behaviour

The application logs me in.

## Context

- Fedora 31, Firefox 76, all AdBlockers disabled
- Eventually this is on the pod side of things, as I cannot test with another identity.
- Something must be happening on their pod: Trying to open https://yala.solid.community/profile/card#me shows an unknown UI to me that throws Strange errors.
- It also fails on https://dokie.li, where I had been logged in successfully up until now.

---

Now that I have written this here, I keep it for reference upstream.

**Comment by almereyda** [comment]
The upstream issue is now https://gitlab.com/solid.community/support/-/issues/21

**Comment by scenaristeur** [comment]
Updated the solid-auth-client as said here https://gitlab.com/solid.community/support/-/issues/21
Do you always have the issue?🤔

**Comment by scenaristeur** [comment]
No news ?
